[package]
name = "nixy-thesis-typst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Moritz Jörg", "Ole Tytlandsvik"]
license = "EUPL-1.2-or-later"
description = "A Nixy thesis template in Typst."
repository = "https://github.com/mrtz-j/typst-thesis-template"
categories = ["thesis"]
keywords = ["thesis", "master", "uit", "bachelor", "university"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"