# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Build thesis

on:
  pull_request:
    paths:
      - "assets/*"
      - "module/*"
      - "template/*"
      - "lib.typ"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          lfs: true
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build Thesis
        run: nix -Lv build .#default
      - name: Upload Release Asset - Assignment
        id: upload
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./result/thesis.pdf
          name: thesis.pdf
          retention-days: 5
      - name: Comment PR Link
        uses: thollander/actions-comment-pull-request@v3
        with:
          reactions: eyes, rocket
          comment-tag: file-upload
          message: |
            Thank you for your contribution. Review ready at: ${{ steps.upload.outputs.artifact-url }}
