name: Build thesis

on:
  pull_request:

permissions:
  contents: write
  
jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          lfs: true

      - uses: typst-community/setup-typst@v3
      - run: typst compile thesis.typ thesis.pdf
      - run: typst compile proposal.typ proposal.pdf
      
      - name: Upload Release Asset - Assignment
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./thesis.pdf
          name: thesis.pdf
          
      - name: Comment PR Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: to_delete
          mode: delete
          reactions: eyes, rocket
          message: |
            Thank you for your contribution. Review ready at: ${{ steps.upload-artifacts.outputs.artifact-url }}
