name: Build thesis

on:
  pull_request:

permissions:
  contents: read
jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          lfs: true

      - uses: typst-community/setup-typst@v3
      - run: typst compile thesis.typ thesis.pdf
      - run: typst compile proposal.typ proposal.pdf
