name: Build thesis

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          lfs: true

      - uses: typst-community/setup-typst@v3
      - run: typst compile ./template/thesis.typ thesis.pdf --root "./"
      # NOTE: Update proposal.typ and comment out the following line if you want to build the proposal.
      # - run: typst compile proposal.typ proposal.pdf
      
      - name: Upload Release Asset - Assignment
        id: upload
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./thesis.pdf
          name: thesis.pdf
          retention-days: 5
          
      - name: Comment PR Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          reactions: eyes, rocket
          message: |
            Thank you for your contribution. Review ready at: ${{ steps.upload.outputs.artifact-url }}
