# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Build and Release thesis

on:
  check_suite:
    types: [completed]

permissions:
  contents: write

jobs:
  build_release_thesis:
    # Ideally, we would regex for semver format, but not possible with gh workflows...
    if: ${{ ! (github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build Thesis
        run: nix -Lv build --accept-flake-config .#default
      - name: Bump Version
        run: |
          nix -Lv develop .#default -c sd 'version = "[0-9]+\.[0-9]+\.[0-9]+"' 'version = \"${{ github.ref_name }}\"' typst.toml
          nix -Lv develop .#default -c sd 'modern-uit-thesis:[0-9]+\.[0-9]+\.[0-9]+' 'modern-uit-thesis:${{ github.ref_name }}' README.md
      - name: Commit Bumped Version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am 'Automated version bump'
          git push
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            result/thesis.pdf
